function export_hls_vectors(Wd, Wr, scen, nFrames)
% EXPORT_HLS_VECTORS  Write ROM tables and bit-true test vectors for the HLS code.
%   Wd      : data word length [bits]
%   Wr      : ROM (twiddle and chirp) word length [bits]
%   scen    : scenario name, sets the AFDM chirp c1 (e.g. 'LEO-Ka')
%   nFrames : number of random test frames per block
%
% Output (under hls/generated/):
%   R<Wr>_<scen>/rom_tables.h        twiddle and chirp ROMs, already quantized
%   W<Wd>_R<Wr>_<scen>/<block>.txt   one line per sample: in_re in_im out_re out_im
% All values are dyadic fractions, printed with %.17g, so they are exact.
p   = sys_params(scen);
fxc = fx_config(Wd, Wr, Wr);
tag = strrep(scen, '-', '');
gen = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'hls', 'generated');
romDir = fullfile(gen, sprintf('R%d_%s', Wr, tag));
vecDir = fullfile(gen, sprintf('W%d_R%d_%s', Wd, Wr, tag));
if ~exist(romDir, 'dir'), mkdir(romDir); end
if ~exist(vecDir, 'dir'), mkdir(vecDir); end

% ---- ROM header ----
[ch1, ch2] = afdm_chirps(p, fxc);
k256 = (0:p.N / 2 - 1).';
k16  = (0:p.K / 2 - 1).';
f = fopen(fullfile(romDir, 'rom_tables.h'), 'w');
fprintf(f, '// Generated by export_hls_vectors.m - do not edit.\n');
fprintf(f, '// ROM width %d bits, scenario %s (2*N*c1 = %g, c2 = %.17g)\n', Wr, scen, 2 * p.N * p.c1, p.c2);
fprintf(f, '#pragma once\n#include "types.h"\n\n');
write_table(f, 'TW256_FWD', fx(exp(-1j * 2 * pi * k256 / 256), fxc.tw));
write_table(f, 'TW256_INV', fx(exp(+1j * 2 * pi * k256 / 256), fxc.tw));
write_table(f, 'TW16_FWD',  fx(exp(-1j * 2 * pi * k16 / 16), fxc.tw));
write_table(f, 'TW16_INV',  fx(exp(+1j * 2 * pi * k16 / 16), fxc.tw));
write_table(f, 'CHIRP1', ch1);                 % exp(-j 2 pi c1 n^2), quantized
write_table(f, 'CHIRP2', ch2);                 % exp(-j 2 pi c2 n^2), quantized
fclose(f);

% ---- Test vectors ----
blocks = {'afdm_mod',       @(v) afdm_mod(v, p, fxc)
          'afdm_demod',     @(v) afdm_demod(v, p, fxc)
          'otfs_zak_mod',   @(v) otfs_mod_zak(v, p, fxc)
          'otfs_zak_demod', @(v) otfs_demod_zak(v, p, fxc)
          'otfs_isfft_mod', @(v) otfs_mod_isfft(v, p, fxc)
          'otfs_sfft_demod',@(v) otfs_demod_sfft(v, p, fxc)};
rng(7);
for b = 1:size(blocks, 1)
    f = fopen(fullfile(vecDir, [blocks{b, 1} '.txt']), 'w');
    for fr = 1:nFrames
        v   = fx((randn(p.N, 1) + 1j * randn(p.N, 1)) / sqrt(2), fxc.data);   % unit power
        out = blocks{b, 2}(v);
        fprintf(f, '%.17g %.17g %.17g %.17g\n', [real(v) imag(v) real(out) imag(out)].');
    end
    fclose(f);
end
fprintf('Exported ROMs to %s and %d frames/block to %s\n', romDir, nFrames, vecDir);
end

function write_table(f, name, z)
% WRITE_TABLE  Emit a const crom array with exact values.
fprintf(f, 'static const crom %s[%d] = {\n', name, numel(z));
fprintf(f, '    {%.17g, %.17g},\n', [real(z) imag(z)].');
fprintf(f, '};\n\n');
end
