// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module afdm_mod_top_chirp_mul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_re_val,
        x_im_val,
        c_re_val,
        c_im_val,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] x_re_val;
input  [11:0] x_im_val;
input  [15:0] c_re_val;
input  [14:0] c_im_val;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [26:0] mul_ln11_fu_76_p2;
reg   [26:0] mul_ln11_reg_468;
wire    ap_block_pp0_stage0_11001;
wire   [25:0] mul_ln11_1_fu_90_p2;
reg   [25:0] mul_ln11_1_reg_473;
wire   [26:0] mul_ln12_fu_100_p2;
reg   [26:0] mul_ln12_reg_478;
wire   [25:0] mul_ln12_1_fu_110_p2;
reg   [25:0] mul_ln12_1_reg_483;
wire    ap_block_pp0_stage0;
wire  signed [11:0] sext_ln11_1_fu_72_p0;
wire  signed [15:0] mul_ln11_fu_76_p0;
wire  signed [26:0] sext_ln11_fu_68_p1;
wire  signed [11:0] sext_ln11_3_fu_86_p0;
wire  signed [14:0] mul_ln11_1_fu_90_p0;
wire  signed [25:0] sext_ln11_2_fu_82_p1;
wire  signed [11:0] sext_ln12_fu_96_p0;
wire  signed [15:0] mul_ln12_fu_100_p0;
wire  signed [11:0] sext_ln12_1_fu_106_p0;
wire  signed [14:0] mul_ln12_1_fu_110_p0;
wire   [26:0] shl_ln11_1_fu_123_p3;
wire  signed [27:0] sext_ln11_4_fu_130_p1;
wire   [27:0] shl_ln_fu_116_p3;
wire   [26:0] shl_ln12_1_fu_147_p3;
wire   [27:0] shl_ln1_fu_140_p3;
wire  signed [27:0] sext_ln12_2_fu_154_p1;
wire   [27:0] re_fu_134_p2;
wire   [0:0] tmp_1_fu_182_p3;
wire   [11:0] trunc_ln_fu_172_p4;
wire   [11:0] zext_ln18_fu_198_p1;
wire   [11:0] add_ln18_fu_202_p2;
wire   [0:0] tmp_3_fu_208_p3;
wire   [0:0] tmp_2_fu_190_p3;
wire   [0:0] xor_ln18_fu_216_p2;
wire   [0:0] xor_ln18_2_fu_228_p2;
wire   [0:0] tmp_fu_164_p3;
wire   [0:0] or_ln18_2_fu_234_p2;
wire   [0:0] xor_ln18_4_fu_240_p2;
wire   [0:0] xor_ln18_3_fu_252_p2;
wire   [0:0] or_ln18_fu_258_p2;
wire   [0:0] xor_ln18_1_fu_246_p2;
wire   [0:0] and_ln18_fu_222_p2;
wire   [0:0] or_ln18_3_fu_270_p2;
wire   [0:0] xor_ln18_5_fu_276_p2;
wire   [0:0] and_ln18_1_fu_264_p2;
wire   [0:0] and_ln18_2_fu_282_p2;
wire   [0:0] or_ln18_1_fu_296_p2;
wire   [11:0] select_ln18_fu_288_p3;
wire   [27:0] im_fu_158_p2;
wire   [0:0] tmp_5_fu_328_p3;
wire   [11:0] trunc_ln1_fu_318_p4;
wire   [11:0] zext_ln19_fu_344_p1;
wire   [11:0] add_ln19_fu_348_p2;
wire   [0:0] tmp_7_fu_354_p3;
wire   [0:0] tmp_6_fu_336_p3;
wire   [0:0] xor_ln19_fu_362_p2;
wire   [0:0] xor_ln19_2_fu_374_p2;
wire   [0:0] tmp_4_fu_310_p3;
wire   [0:0] or_ln19_2_fu_380_p2;
wire   [0:0] xor_ln19_4_fu_386_p2;
wire   [0:0] xor_ln19_3_fu_398_p2;
wire   [0:0] or_ln19_fu_404_p2;
wire   [0:0] xor_ln19_1_fu_392_p2;
wire   [0:0] and_ln19_fu_368_p2;
wire   [0:0] or_ln19_3_fu_416_p2;
wire   [0:0] xor_ln19_5_fu_422_p2;
wire   [0:0] and_ln19_1_fu_410_p2;
wire   [0:0] and_ln19_2_fu_428_p2;
wire   [0:0] or_ln19_1_fu_442_p2;
wire   [11:0] select_ln19_fu_434_p3;
wire   [11:0] y_re_fu_302_p3;
wire   [11:0] y_im_fu_448_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_init_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

afdm_mod_top_mul_16s_12s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 27 ))
mul_16s_12s_27_1_1_U5(
    .din0(mul_ln11_fu_76_p0),
    .din1(sext_ln11_1_fu_72_p0),
    .dout(mul_ln11_fu_76_p2)
);

afdm_mod_top_mul_15s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_15s_12s_26_1_1_U6(
    .din0(mul_ln11_1_fu_90_p0),
    .din1(sext_ln11_3_fu_86_p0),
    .dout(mul_ln11_1_fu_90_p2)
);

afdm_mod_top_mul_16s_12s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 27 ))
mul_16s_12s_27_1_1_U7(
    .din0(mul_ln12_fu_100_p0),
    .din1(sext_ln12_fu_96_p0),
    .dout(mul_ln12_fu_100_p2)
);

afdm_mod_top_mul_15s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_15s_12s_26_1_1_U8(
    .din0(mul_ln12_1_fu_110_p0),
    .din1(sext_ln12_1_fu_106_p0),
    .dout(mul_ln12_1_fu_110_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln11_1_reg_473 <= mul_ln11_1_fu_90_p2;
        mul_ln11_reg_468 <= mul_ln11_fu_76_p2;
        mul_ln12_1_reg_483 <= mul_ln12_1_fu_110_p2;
        mul_ln12_reg_478 <= mul_ln12_fu_100_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to0 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_fu_202_p2 = (trunc_ln_fu_172_p4 + zext_ln18_fu_198_p1);

assign add_ln19_fu_348_p2 = (trunc_ln1_fu_318_p4 + zext_ln19_fu_344_p1);

assign and_ln18_1_fu_264_p2 = (xor_ln18_1_fu_246_p2 & or_ln18_fu_258_p2);

assign and_ln18_2_fu_282_p2 = (xor_ln18_5_fu_276_p2 & tmp_fu_164_p3);

assign and_ln18_fu_222_p2 = (xor_ln18_fu_216_p2 & tmp_2_fu_190_p3);

assign and_ln19_1_fu_410_p2 = (xor_ln19_1_fu_392_p2 & or_ln19_fu_404_p2);

assign and_ln19_2_fu_428_p2 = (xor_ln19_5_fu_422_p2 & tmp_4_fu_310_p3);

assign and_ln19_fu_368_p2 = (xor_ln19_fu_362_p2 & tmp_6_fu_336_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = y_re_fu_302_p3;

assign ap_return_1 = y_im_fu_448_p3;

assign im_fu_158_p2 = ($signed(shl_ln1_fu_140_p3) - $signed(sext_ln12_2_fu_154_p1));

assign mul_ln11_1_fu_90_p0 = sext_ln11_2_fu_82_p1;

assign mul_ln11_fu_76_p0 = sext_ln11_fu_68_p1;

assign mul_ln12_1_fu_110_p0 = sext_ln11_2_fu_82_p1;

assign mul_ln12_fu_100_p0 = sext_ln11_fu_68_p1;

assign or_ln18_1_fu_296_p2 = (and_ln18_2_fu_282_p2 | and_ln18_1_fu_264_p2);

assign or_ln18_2_fu_234_p2 = (xor_ln18_2_fu_228_p2 | tmp_3_fu_208_p3);

assign or_ln18_3_fu_270_p2 = (tmp_3_fu_208_p3 | and_ln18_fu_222_p2);

assign or_ln18_fu_258_p2 = (xor_ln18_3_fu_252_p2 | tmp_3_fu_208_p3);

assign or_ln19_1_fu_442_p2 = (and_ln19_2_fu_428_p2 | and_ln19_1_fu_410_p2);

assign or_ln19_2_fu_380_p2 = (xor_ln19_2_fu_374_p2 | tmp_7_fu_354_p3);

assign or_ln19_3_fu_416_p2 = (tmp_7_fu_354_p3 | and_ln19_fu_368_p2);

assign or_ln19_fu_404_p2 = (xor_ln19_3_fu_398_p2 | tmp_7_fu_354_p3);

assign re_fu_134_p2 = ($signed(sext_ln11_4_fu_130_p1) + $signed(shl_ln_fu_116_p3));

assign select_ln18_fu_288_p3 = ((and_ln18_1_fu_264_p2[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign select_ln19_fu_434_p3 = ((and_ln19_1_fu_410_p2[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign sext_ln11_1_fu_72_p0 = x_re_val;

assign sext_ln11_2_fu_82_p1 = $signed(c_im_val);

assign sext_ln11_3_fu_86_p0 = x_im_val;

assign sext_ln11_4_fu_130_p1 = $signed(shl_ln11_1_fu_123_p3);

assign sext_ln11_fu_68_p1 = $signed(c_re_val);

assign sext_ln12_1_fu_106_p0 = x_re_val;

assign sext_ln12_2_fu_154_p1 = $signed(shl_ln12_1_fu_147_p3);

assign sext_ln12_fu_96_p0 = x_im_val;

assign shl_ln11_1_fu_123_p3 = {{mul_ln11_1_reg_473}, {1'd0}};

assign shl_ln12_1_fu_147_p3 = {{mul_ln12_1_reg_483}, {1'd0}};

assign shl_ln1_fu_140_p3 = {{mul_ln12_reg_478}, {1'd0}};

assign shl_ln_fu_116_p3 = {{mul_ln11_reg_468}, {1'd0}};

assign tmp_1_fu_182_p3 = re_fu_134_p2[32'd14];

assign tmp_2_fu_190_p3 = re_fu_134_p2[32'd26];

assign tmp_3_fu_208_p3 = add_ln18_fu_202_p2[32'd11];

assign tmp_4_fu_310_p3 = im_fu_158_p2[32'd27];

assign tmp_5_fu_328_p3 = im_fu_158_p2[32'd14];

assign tmp_6_fu_336_p3 = im_fu_158_p2[32'd26];

assign tmp_7_fu_354_p3 = add_ln19_fu_348_p2[32'd11];

assign tmp_fu_164_p3 = re_fu_134_p2[32'd27];

assign trunc_ln1_fu_318_p4 = {{im_fu_158_p2[26:15]}};

assign trunc_ln_fu_172_p4 = {{re_fu_134_p2[26:15]}};

assign xor_ln18_1_fu_246_p2 = (tmp_fu_164_p3 ^ 1'd1);

assign xor_ln18_2_fu_228_p2 = (tmp_2_fu_190_p3 ^ 1'd1);

assign xor_ln18_3_fu_252_p2 = (xor_ln18_4_fu_240_p2 ^ 1'd1);

assign xor_ln18_4_fu_240_p2 = (tmp_fu_164_p3 ^ or_ln18_2_fu_234_p2);

assign xor_ln18_5_fu_276_p2 = (or_ln18_3_fu_270_p2 ^ 1'd1);

assign xor_ln18_fu_216_p2 = (tmp_3_fu_208_p3 ^ 1'd1);

assign xor_ln19_1_fu_392_p2 = (tmp_4_fu_310_p3 ^ 1'd1);

assign xor_ln19_2_fu_374_p2 = (tmp_6_fu_336_p3 ^ 1'd1);

assign xor_ln19_3_fu_398_p2 = (xor_ln19_4_fu_386_p2 ^ 1'd1);

assign xor_ln19_4_fu_386_p2 = (tmp_4_fu_310_p3 ^ or_ln19_2_fu_380_p2);

assign xor_ln19_5_fu_422_p2 = (or_ln19_3_fu_416_p2 ^ 1'd1);

assign xor_ln19_fu_362_p2 = (tmp_7_fu_354_p3 ^ 1'd1);

assign y_im_fu_448_p3 = ((or_ln19_1_fu_442_p2[0:0] == 1'b1) ? select_ln19_fu_434_p3 : add_ln19_fu_348_p2);

assign y_re_fu_302_p3 = ((or_ln18_1_fu_296_p2[0:0] == 1'b1) ? select_ln18_fu_288_p3 : add_ln18_fu_202_p2);

assign zext_ln18_fu_198_p1 = tmp_1_fu_182_p3;

assign zext_ln19_fu_344_p1 = tmp_5_fu_328_p3;

endmodule //afdm_mod_top_chirp_mul
