// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module afdm_mod_top_afdm_mod (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_re_address0,
        x_re_ce0,
        x_re_q0,
        x_im_address0,
        x_im_ce0,
        x_im_q0,
        s_re_address0,
        s_re_ce0,
        s_re_we0,
        s_re_d0,
        s_im_address0,
        s_im_ce0,
        s_im_we0,
        s_im_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] x_re_address0;
output   x_re_ce0;
input  [11:0] x_re_q0;
output  [7:0] x_im_address0;
output   x_im_ce0;
input  [11:0] x_im_q0;
output  [7:0] s_re_address0;
output   s_re_ce0;
output   s_re_we0;
output  [11:0] s_re_d0;
output  [7:0] s_im_address0;
output   s_im_ce0;
output   s_im_we0;
output  [11:0] s_im_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] tmp_re_address0;
reg    tmp_re_ce0;
reg    tmp_re_we0;
reg   [11:0] tmp_re_d0;
wire   [11:0] tmp_re_q0;
reg    tmp_re_ce1;
reg    tmp_re_we1;
wire   [11:0] tmp_re_q1;
reg   [7:0] tmp_im_address0;
reg    tmp_im_ce0;
reg    tmp_im_we0;
reg   [11:0] tmp_im_d0;
wire   [11:0] tmp_im_q0;
reg    tmp_im_ce1;
reg    tmp_im_we1;
wire   [11:0] tmp_im_q1;
reg   [7:0] buf_re_address0;
reg    buf_re_ce0;
reg    buf_re_we0;
reg   [11:0] buf_re_d0;
wire   [11:0] buf_re_q0;
reg   [7:0] buf_im_address0;
reg    buf_im_ce0;
reg    buf_im_we0;
reg   [11:0] buf_im_d0;
wire   [11:0] buf_im_q0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_done;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_idle;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_ready;
wire   [7:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_address0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_address0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_address0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_ce0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_we0;
wire   [11:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_d0;
wire   [7:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_address0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_ce0;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_we0;
wire   [11:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_d0;
wire   [11:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din1;
wire   [11:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din2;
wire   [15:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din3;
wire   [14:0] grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din4;
wire    grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_start;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_ap_start;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_ap_done;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_ap_idle;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_ap_ready;
wire   [7:0] grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_address0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_address0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_address0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_ce0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_we0;
wire   [11:0] grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_d0;
wire   [7:0] grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_address0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_ce0;
wire    grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_we0;
wire   [11:0] grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_d0;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_done;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_idle;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_ready;
wire   [7:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address0;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce0;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we0;
wire   [11:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d0;
wire   [7:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address1;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce1;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we1;
wire   [11:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d1;
wire   [7:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address0;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce0;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we0;
wire   [11:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d0;
wire   [7:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address1;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce1;
wire    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we1;
wire   [11:0] grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d1;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_ap_done;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_ap_idle;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_ap_ready;
wire   [7:0] grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_address0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_address0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_address0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_ce0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_we0;
wire   [11:0] grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_d0;
wire   [7:0] grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_address0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_ce0;
wire    grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_we0;
wire   [11:0] grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_d0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_idle;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_ready;
wire   [7:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_address0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_address0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_ce0;
wire   [7:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_address0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_ce0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_we0;
wire   [11:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_d0;
wire   [7:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_address0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_ce0;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_we0;
wire   [11:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_d0;
wire   [11:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din1;
wire   [11:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din2;
wire   [15:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din3;
wire   [14:0] grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din4;
wire    grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_start;
reg    grp_chirp_mul_fu_104_ap_start;
wire    grp_chirp_mul_fu_104_ap_done;
wire    grp_chirp_mul_fu_104_ap_idle;
wire    grp_chirp_mul_fu_104_ap_ready;
reg   [11:0] grp_chirp_mul_fu_104_x_re_val;
reg   [11:0] grp_chirp_mul_fu_104_x_im_val;
reg   [15:0] grp_chirp_mul_fu_104_c_re_val;
reg   [14:0] grp_chirp_mul_fu_104_c_im_val;
wire   [11:0] grp_chirp_mul_fu_104_ap_return_0;
wire   [11:0] grp_chirp_mul_fu_104_ap_return_1;
reg    grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg = 1'b0;
#0 grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg = 1'b0;
#0 grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg = 1'b0;
#0 grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg = 1'b0;
#0 grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg = 1'b0;
end

afdm_mod_top_afdm_mod_tmp_re_RAM_AUTO_1R1W #(
    .DataWidth( 12 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
tmp_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_re_address0),
    .ce0(tmp_re_ce0),
    .we0(tmp_re_we0),
    .d0(tmp_re_d0),
    .q0(tmp_re_q0),
    .address1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address1),
    .ce1(tmp_re_ce1),
    .we1(tmp_re_we1),
    .d1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d1),
    .q1(tmp_re_q1)
);

afdm_mod_top_afdm_mod_tmp_re_RAM_AUTO_1R1W #(
    .DataWidth( 12 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
tmp_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_im_address0),
    .ce0(tmp_im_ce0),
    .we0(tmp_im_we0),
    .d0(tmp_im_d0),
    .q0(tmp_im_q0),
    .address1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address1),
    .ce1(tmp_im_ce1),
    .we1(tmp_im_we1),
    .d1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d1),
    .q1(tmp_im_q1)
);

afdm_mod_top_afdm_mod_buf_re_RAM_AUTO_1R1W #(
    .DataWidth( 12 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buf_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_re_address0),
    .ce0(buf_re_ce0),
    .we0(buf_re_we0),
    .d0(buf_re_d0),
    .q0(buf_re_q0)
);

afdm_mod_top_afdm_mod_buf_re_RAM_AUTO_1R1W #(
    .DataWidth( 12 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buf_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_im_address0),
    .ce0(buf_im_ce0),
    .we0(buf_im_we0),
    .d0(buf_im_d0),
    .q0(buf_im_q0)
);

afdm_mod_top_afdm_mod_Pipeline_pre_chirp grp_afdm_mod_Pipeline_pre_chirp_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start),
    .ap_done(grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_done),
    .ap_idle(grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_idle),
    .ap_ready(grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_ready),
    .x_re_address0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_address0),
    .x_re_ce0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_ce0),
    .x_re_q0(x_re_q0),
    .x_im_address0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_address0),
    .x_im_ce0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_ce0),
    .x_im_q0(x_im_q0),
    .buf_re_address0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_address0),
    .buf_re_ce0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_ce0),
    .buf_re_we0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_we0),
    .buf_re_d0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_d0),
    .buf_im_address0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_address0),
    .buf_im_ce0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_ce0),
    .buf_im_we0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_we0),
    .buf_im_d0(grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_d0),
    .grp_chirp_mul_fu_104_p_din1(grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din1),
    .grp_chirp_mul_fu_104_p_din2(grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din2),
    .grp_chirp_mul_fu_104_p_din3(grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din3),
    .grp_chirp_mul_fu_104_p_din4(grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din4),
    .grp_chirp_mul_fu_104_p_dout0_0(grp_chirp_mul_fu_104_ap_return_0),
    .grp_chirp_mul_fu_104_p_dout0_1(grp_chirp_mul_fu_104_ap_return_1),
    .grp_chirp_mul_fu_104_p_start(grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_start),
    .grp_chirp_mul_fu_104_p_ready(grp_chirp_mul_fu_104_ap_ready),
    .grp_chirp_mul_fu_104_p_done(grp_chirp_mul_fu_104_ap_done),
    .grp_chirp_mul_fu_104_p_idle(grp_chirp_mul_fu_104_ap_idle)
);

afdm_mod_top_afdm_mod_Pipeline_reorder grp_afdm_mod_Pipeline_reorder_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_afdm_mod_Pipeline_reorder_fu_64_ap_start),
    .ap_done(grp_afdm_mod_Pipeline_reorder_fu_64_ap_done),
    .ap_idle(grp_afdm_mod_Pipeline_reorder_fu_64_ap_idle),
    .ap_ready(grp_afdm_mod_Pipeline_reorder_fu_64_ap_ready),
    .buf_re_address0(grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_address0),
    .buf_re_ce0(grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_ce0),
    .buf_re_q0(buf_re_q0),
    .buf_im_address0(grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_address0),
    .buf_im_ce0(grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_ce0),
    .buf_im_q0(buf_im_q0),
    .tmp_re_address0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_address0),
    .tmp_re_ce0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_ce0),
    .tmp_re_we0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_we0),
    .tmp_re_d0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_d0),
    .tmp_im_address0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_address0),
    .tmp_im_ce0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_ce0),
    .tmp_im_we0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_we0),
    .tmp_im_d0(grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_d0)
);

afdm_mod_top_afdm_mod_Pipeline_stages_butterflies grp_afdm_mod_Pipeline_stages_butterflies_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start),
    .ap_done(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_done),
    .ap_idle(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_idle),
    .ap_ready(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_ready),
    .tmp_re_address0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address0),
    .tmp_re_ce0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce0),
    .tmp_re_we0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we0),
    .tmp_re_d0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d0),
    .tmp_re_q0(tmp_re_q0),
    .tmp_re_address1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address1),
    .tmp_re_ce1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce1),
    .tmp_re_we1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we1),
    .tmp_re_d1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d1),
    .tmp_re_q1(tmp_re_q1),
    .tmp_im_address0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address0),
    .tmp_im_ce0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce0),
    .tmp_im_we0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we0),
    .tmp_im_d0(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d0),
    .tmp_im_q0(tmp_im_q0),
    .tmp_im_address1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address1),
    .tmp_im_ce1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce1),
    .tmp_im_we1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we1),
    .tmp_im_d1(grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d1),
    .tmp_im_q1(tmp_im_q1)
);

afdm_mod_top_afdm_mod_Pipeline_copy_out grp_afdm_mod_Pipeline_copy_out_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start),
    .ap_done(grp_afdm_mod_Pipeline_copy_out_fu_82_ap_done),
    .ap_idle(grp_afdm_mod_Pipeline_copy_out_fu_82_ap_idle),
    .ap_ready(grp_afdm_mod_Pipeline_copy_out_fu_82_ap_ready),
    .tmp_re_address0(grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_address0),
    .tmp_re_ce0(grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_ce0),
    .tmp_re_q0(tmp_re_q0),
    .tmp_im_address0(grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_address0),
    .tmp_im_ce0(grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_ce0),
    .tmp_im_q0(tmp_im_q0),
    .buf_re_address0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_address0),
    .buf_re_ce0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_ce0),
    .buf_re_we0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_we0),
    .buf_re_d0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_d0),
    .buf_im_address0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_address0),
    .buf_im_ce0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_ce0),
    .buf_im_we0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_we0),
    .buf_im_d0(grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_d0)
);

afdm_mod_top_afdm_mod_Pipeline_post_chirp grp_afdm_mod_Pipeline_post_chirp_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start),
    .ap_done(grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done),
    .ap_idle(grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_idle),
    .ap_ready(grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_ready),
    .buf_re_address0(grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_address0),
    .buf_re_ce0(grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_ce0),
    .buf_re_q0(buf_re_q0),
    .buf_im_address0(grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_address0),
    .buf_im_ce0(grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_ce0),
    .buf_im_q0(buf_im_q0),
    .s_re_address0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_address0),
    .s_re_ce0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_ce0),
    .s_re_we0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_we0),
    .s_re_d0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_d0),
    .s_im_address0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_address0),
    .s_im_ce0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_ce0),
    .s_im_we0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_we0),
    .s_im_d0(grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_d0),
    .grp_chirp_mul_fu_104_p_din1(grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din1),
    .grp_chirp_mul_fu_104_p_din2(grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din2),
    .grp_chirp_mul_fu_104_p_din3(grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din3),
    .grp_chirp_mul_fu_104_p_din4(grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din4),
    .grp_chirp_mul_fu_104_p_dout0_0(grp_chirp_mul_fu_104_ap_return_0),
    .grp_chirp_mul_fu_104_p_dout0_1(grp_chirp_mul_fu_104_ap_return_1),
    .grp_chirp_mul_fu_104_p_start(grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_start),
    .grp_chirp_mul_fu_104_p_ready(grp_chirp_mul_fu_104_ap_ready),
    .grp_chirp_mul_fu_104_p_done(grp_chirp_mul_fu_104_ap_done),
    .grp_chirp_mul_fu_104_p_idle(grp_chirp_mul_fu_104_ap_idle)
);

afdm_mod_top_chirp_mul grp_chirp_mul_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_chirp_mul_fu_104_ap_start),
    .ap_done(grp_chirp_mul_fu_104_ap_done),
    .ap_idle(grp_chirp_mul_fu_104_ap_idle),
    .ap_ready(grp_chirp_mul_fu_104_ap_ready),
    .x_re_val(grp_chirp_mul_fu_104_x_re_val),
    .x_im_val(grp_chirp_mul_fu_104_x_im_val),
    .c_re_val(grp_chirp_mul_fu_104_c_re_val),
    .c_im_val(grp_chirp_mul_fu_104_c_im_val),
    .ap_return_0(grp_chirp_mul_fu_104_ap_return_0),
    .ap_return_1(grp_chirp_mul_fu_104_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_afdm_mod_Pipeline_copy_out_fu_82_ap_ready == 1'b1)) begin
            grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_ready == 1'b1)) begin
            grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_ready == 1'b1)) begin
            grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_afdm_mod_Pipeline_reorder_fu_64_ap_ready == 1'b1)) begin
            grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_ready == 1'b1)) begin
            grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_afdm_mod_Pipeline_reorder_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_afdm_mod_Pipeline_copy_out_fu_82_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_im_address0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_address0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_im_address0 = grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_im_address0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_address0;
    end else begin
        buf_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_im_ce0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_ce0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_im_ce0 = grp_afdm_mod_Pipeline_reorder_fu_64_buf_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_im_ce0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_ce0;
    end else begin
        buf_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_d0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_im_d0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_d0;
    end else begin
        buf_im_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_we0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_im_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_im_we0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_im_we0;
    end else begin
        buf_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_re_address0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_address0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_re_address0 = grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_re_address0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_address0;
    end else begin
        buf_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_re_ce0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_buf_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_ce0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_re_ce0 = grp_afdm_mod_Pipeline_reorder_fu_64_buf_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_re_ce0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_ce0;
    end else begin
        buf_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_d0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_re_d0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_d0;
    end else begin
        buf_re_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_we0 = grp_afdm_mod_Pipeline_copy_out_fu_82_buf_re_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_re_we0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_buf_re_we0;
    end else begin
        buf_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_chirp_mul_fu_104_ap_start = grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_start;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_chirp_mul_fu_104_ap_start = grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_start;
    end else begin
        grp_chirp_mul_fu_104_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_chirp_mul_fu_104_c_im_val = grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_chirp_mul_fu_104_c_im_val = grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din4;
    end else begin
        grp_chirp_mul_fu_104_c_im_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_chirp_mul_fu_104_c_re_val = grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_chirp_mul_fu_104_c_re_val = grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din3;
    end else begin
        grp_chirp_mul_fu_104_c_re_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_chirp_mul_fu_104_x_im_val = grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_chirp_mul_fu_104_x_im_val = grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din2;
    end else begin
        grp_chirp_mul_fu_104_x_im_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_chirp_mul_fu_104_x_re_val = grp_afdm_mod_Pipeline_post_chirp_fu_90_grp_chirp_mul_fu_104_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_chirp_mul_fu_104_x_re_val = grp_afdm_mod_Pipeline_pre_chirp_fu_48_grp_chirp_mul_fu_104_p_din1;
    end else begin
        grp_chirp_mul_fu_104_x_re_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_im_address0 = grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_address0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_im_address0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_address0;
    end else begin
        tmp_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_im_ce0 = grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_ce0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_im_ce0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_ce0;
    end else begin
        tmp_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_ce1 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_ce1;
    end else begin
        tmp_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_d0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_im_d0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_d0;
    end else begin
        tmp_im_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_we0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_im_we0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_im_we0;
    end else begin
        tmp_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_im_we1 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_im_we1;
    end else begin
        tmp_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_re_address0 = grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_address0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_re_address0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_address0;
    end else begin
        tmp_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_re_ce0 = grp_afdm_mod_Pipeline_copy_out_fu_82_tmp_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_ce0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_re_ce0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_ce0;
    end else begin
        tmp_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_ce1 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_ce1;
    end else begin
        tmp_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_d0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_re_d0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_d0;
    end else begin
        tmp_re_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_we0 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_re_we0 = grp_afdm_mod_Pipeline_reorder_fu_64_tmp_re_we0;
    end else begin
        tmp_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_re_we1 = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_tmp_re_we1;
    end else begin
        tmp_re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_afdm_mod_Pipeline_reorder_fu_64_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_afdm_mod_Pipeline_copy_out_fu_82_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start = grp_afdm_mod_Pipeline_copy_out_fu_82_ap_start_reg;

assign grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start = grp_afdm_mod_Pipeline_post_chirp_fu_90_ap_start_reg;

assign grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start = grp_afdm_mod_Pipeline_pre_chirp_fu_48_ap_start_reg;

assign grp_afdm_mod_Pipeline_reorder_fu_64_ap_start = grp_afdm_mod_Pipeline_reorder_fu_64_ap_start_reg;

assign grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start = grp_afdm_mod_Pipeline_stages_butterflies_fu_72_ap_start_reg;

assign s_im_address0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_address0;

assign s_im_ce0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_ce0;

assign s_im_d0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_d0;

assign s_im_we0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_im_we0;

assign s_re_address0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_address0;

assign s_re_ce0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_ce0;

assign s_re_d0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_d0;

assign s_re_we0 = grp_afdm_mod_Pipeline_post_chirp_fu_90_s_re_we0;

assign x_im_address0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_address0;

assign x_im_ce0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_im_ce0;

assign x_re_address0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_address0;

assign x_re_ce0 = grp_afdm_mod_Pipeline_pre_chirp_fu_48_x_re_ce0;

endmodule //afdm_mod_top_afdm_mod
