// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module afdm_mod_top_afdm_mod_Pipeline_stages_butterflies (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_re_address0,
        tmp_re_ce0,
        tmp_re_we0,
        tmp_re_d0,
        tmp_re_q0,
        tmp_re_address1,
        tmp_re_ce1,
        tmp_re_we1,
        tmp_re_d1,
        tmp_re_q1,
        tmp_im_address0,
        tmp_im_ce0,
        tmp_im_we0,
        tmp_im_d0,
        tmp_im_q0,
        tmp_im_address1,
        tmp_im_ce1,
        tmp_im_we1,
        tmp_im_d1,
        tmp_im_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] tmp_re_address0;
output   tmp_re_ce0;
output   tmp_re_we0;
output  [11:0] tmp_re_d0;
input  [11:0] tmp_re_q0;
output  [7:0] tmp_re_address1;
output   tmp_re_ce1;
output   tmp_re_we1;
output  [11:0] tmp_re_d1;
input  [11:0] tmp_re_q1;
output  [7:0] tmp_im_address0;
output   tmp_im_ce0;
output   tmp_im_we0;
output  [11:0] tmp_im_d0;
input  [11:0] tmp_im_q0;
output  [7:0] tmp_im_address1;
output   tmp_im_ce1;
output   tmp_im_we1;
output  [11:0] tmp_im_d1;
input  [11:0] tmp_im_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln58_reg_1449;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] TW256_INV_re_address0;
wire   [15:0] TW256_INV_re_q0;
wire   [6:0] TW256_INV_im_address0;
wire   [14:0] TW256_INV_im_q0;
wire   [0:0] icmp_ln58_fu_204_p2;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] s_load_reg_1453;
wire   [0:0] icmp_ln61_fu_222_p2;
reg   [0:0] icmp_ln61_reg_1458;
wire   [7:0] select_ln58_fu_228_p3;
reg   [7:0] select_ln58_reg_1463;
wire   [3:0] add_ln67_1_fu_236_p2;
reg   [3:0] add_ln67_1_reg_1469;
wire   [3:0] select_ln58_2_fu_242_p3;
reg   [3:0] select_ln58_2_reg_1474;
wire   [0:0] trunc_ln58_fu_254_p1;
reg   [0:0] trunc_ln58_reg_1479;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter1_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter2_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter3_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter4_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter5_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter6_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter7_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter8_reg;
reg   [0:0] trunc_ln58_reg_1479_pp0_iter9_reg;
wire   [7:0] half_fu_258_p2;
reg   [7:0] half_reg_1487;
reg   [7:0] half_reg_1487_pp0_iter1_reg;
reg   [7:0] half_reg_1487_pp0_iter2_reg;
reg   [7:0] half_reg_1487_pp0_iter3_reg;
reg   [7:0] half_reg_1487_pp0_iter4_reg;
reg   [7:0] half_reg_1487_pp0_iter5_reg;
reg   [7:0] half_reg_1487_pp0_iter6_reg;
wire   [6:0] trunc_ln59_fu_264_p1;
reg   [6:0] trunc_ln59_reg_1493;
wire   [6:0] trunc_ln61_fu_268_p1;
reg   [6:0] trunc_ln61_reg_1498;
wire    ap_block_pp0_stage1_11001;
wire  signed [6:0] k_fu_321_p2;
reg  signed [6:0] k_reg_1508;
reg  signed [6:0] k_reg_1508_pp0_iter1_reg;
reg  signed [6:0] k_reg_1508_pp0_iter2_reg;
reg  signed [6:0] k_reg_1508_pp0_iter3_reg;
reg  signed [6:0] k_reg_1508_pp0_iter4_reg;
reg  signed [6:0] k_reg_1508_pp0_iter5_reg;
reg  signed [6:0] k_reg_1508_pp0_iter6_reg;
wire   [7:0] trunc_ln67_fu_338_p1;
reg   [7:0] trunc_ln67_reg_1514;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter1_reg;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter2_reg;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter3_reg;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter4_reg;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter5_reg;
reg   [7:0] trunc_ln67_reg_1514_pp0_iter6_reg;
wire   [6:0] grp_fu_312_p2;
reg   [6:0] udiv_ln69_reg_1519;
wire   [7:0] ia_fu_358_p2;
reg   [7:0] ia_reg_1524;
reg   [7:0] bot_re_reg_1529;
reg   [7:0] bot_re_reg_1529_pp0_iter8_reg;
reg   [7:0] bot_re_reg_1529_pp0_iter9_reg;
reg   [7:0] bot_re_reg_1529_pp0_iter10_reg;
reg   [7:0] bot_im_reg_1535;
reg   [7:0] bot_im_reg_1535_pp0_iter8_reg;
reg   [7:0] bot_im_reg_1535_pp0_iter9_reg;
reg   [7:0] bot_im_reg_1535_pp0_iter10_reg;
reg  signed [11:0] tmp_re_load_1_reg_1551;
reg  signed [11:0] tmp_im_load_1_reg_1556;
reg  signed [15:0] TW256_INV_re_load_reg_1561;
reg   [14:0] TW256_INV_im_load_reg_1566;
reg   [7:0] top_re_reg_1571;
reg   [7:0] top_re_reg_1571_pp0_iter9_reg;
reg   [7:0] top_im_reg_1577;
reg   [7:0] top_im_reg_1577_pp0_iter9_reg;
wire  signed [25:0] sext_ln22_fu_390_p1;
reg  signed [25:0] sext_ln22_reg_1583;
wire  signed [25:0] sext_ln22_1_fu_393_p1;
reg  signed [25:0] sext_ln22_1_reg_1588;
wire   [25:0] mul_ln22_fu_396_p2;
reg   [25:0] mul_ln22_reg_1593;
wire   [25:0] zext_ln22_fu_402_p1;
reg   [25:0] zext_ln22_reg_1598;
wire  signed [25:0] sext_ln22_3_fu_405_p1;
reg  signed [25:0] sext_ln22_3_reg_1603;
wire   [25:0] mul_ln22_1_fu_408_p2;
reg   [25:0] mul_ln22_1_reg_1608;
reg   [11:0] tmp_re_load_reg_1613;
reg   [11:0] tmp_im_load_reg_1618;
wire   [27:0] tre_fu_436_p2;
reg   [27:0] tre_reg_1623;
wire   [25:0] mul_ln23_fu_442_p2;
reg   [25:0] mul_ln23_reg_1628;
wire   [25:0] mul_ln23_1_fu_446_p2;
reg   [25:0] mul_ln23_1_reg_1633;
wire   [28:0] dim_fu_525_p2;
reg   [28:0] dim_reg_1638;
reg   [27:0] dim_1_reg_1643;
wire  signed [28:0] sim_2_fu_594_p3;
reg  signed [28:0] sim_2_reg_1648;
wire  signed [30:0] sext_ln31_5_fu_601_p1;
reg  signed [30:0] sext_ln31_5_reg_1653;
wire   [0:0] tmp_fu_616_p3;
reg   [0:0] tmp_reg_1659;
wire   [11:0] add_ln34_fu_654_p2;
reg   [11:0] add_ln34_reg_1664;
wire   [0:0] and_ln34_fu_674_p2;
reg   [0:0] and_ln34_reg_1669;
wire   [0:0] icmp_ln34_fu_706_p2;
reg   [0:0] icmp_ln34_reg_1674;
wire   [0:0] and_ln34_3_fu_764_p2;
reg   [0:0] and_ln34_3_reg_1679;
wire   [0:0] and_ln34_4_fu_770_p2;
reg   [0:0] and_ln34_4_reg_1685;
reg   [0:0] tmp_14_reg_1690;
wire   [11:0] add_ln34_1_fu_806_p2;
reg   [11:0] add_ln34_1_reg_1696;
reg   [0:0] tmp_17_reg_1701;
wire   [0:0] icmp_ln34_2_fu_830_p2;
reg   [0:0] icmp_ln34_2_reg_1708;
wire   [0:0] icmp_ln34_3_fu_836_p2;
reg   [0:0] icmp_ln34_3_reg_1715;
wire   [0:0] tmp_21_fu_842_p3;
reg   [0:0] tmp_21_reg_1720;
wire   [11:0] add_ln35_fu_880_p2;
reg   [11:0] add_ln35_reg_1725;
wire   [0:0] and_ln35_fu_900_p2;
reg   [0:0] and_ln35_reg_1730;
wire   [0:0] icmp_ln35_fu_932_p2;
reg   [0:0] icmp_ln35_reg_1735;
wire   [0:0] and_ln35_3_fu_990_p2;
reg   [0:0] and_ln35_3_reg_1740;
wire   [0:0] and_ln35_4_fu_996_p2;
reg   [0:0] and_ln35_4_reg_1746;
wire   [11:0] select_ln35_3_fu_1215_p3;
reg   [11:0] select_ln35_3_reg_1751;
wire   [11:0] select_ln35_7_fu_1420_p3;
reg   [11:0] select_ln35_7_reg_1756;
wire   [63:0] zext_ln69_2_fu_368_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln69_3_fu_379_p1;
wire   [63:0] zext_ln69_1_fu_385_p1;
reg   [7:0] i_fu_98;
wire   [7:0] i_1_fu_342_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [3:0] s_fu_102;
reg   [3:0] ap_sig_allocacmp_s_load;
reg   [10:0] indvar_flatten_fu_106;
wire   [10:0] add_ln58_fu_210_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    tmp_re_ce1_local;
reg   [7:0] tmp_re_address1_local;
reg    tmp_re_ce0_local;
reg   [7:0] tmp_re_address0_local;
reg    tmp_re_we1_local;
wire   [11:0] select_ln34_3_fu_1047_p3;
wire    ap_block_pp0_stage1;
reg    tmp_re_we0_local;
reg    tmp_im_ce1_local;
reg   [7:0] tmp_im_address1_local;
reg    tmp_im_ce0_local;
reg   [7:0] tmp_im_address0_local;
reg    tmp_im_we1_local;
wire   [11:0] select_ln34_7_fu_1175_p3;
reg    tmp_im_we0_local;
reg    TW256_INV_re_ce0_local;
reg    TW256_INV_im_ce0_local;
wire   [7:0] zext_ln58_1_fu_250_p1;
wire   [3:0] add_ln67_fu_282_p2;
wire   [3:0] select_ln58_1_fu_287_p3;
wire   [8:0] grp_fu_312_p1;
wire   [6:0] add_ln66_fu_296_p2;
wire   [8:0] zext_ln61_fu_318_p1;
wire   [8:0] zext_ln58_fu_293_p1;
wire   [8:0] lshr_ln67_fu_326_p2;
wire   [8:0] zext_ln69_fu_301_p1;
wire   [8:0] shl_ln67_fu_332_p2;
wire   [7:0] zext_ln66_fu_355_p1;
wire   [7:0] ib_fu_363_p2;
wire  signed [6:0] mul_ln69_fu_374_p1;
wire   [6:0] mul_ln69_fu_374_p2;
wire   [14:0] mul_ln22_1_fu_408_p0;
wire   [26:0] shl_ln2_fu_414_p3;
wire   [26:0] shl_ln22_1_fu_425_p3;
wire  signed [27:0] sext_ln22_2_fu_421_p1;
wire  signed [27:0] sext_ln22_4_fu_432_p1;
wire   [14:0] mul_ln23_fu_442_p0;
wire  signed [11:0] mul_ln23_fu_442_p1;
wire  signed [15:0] mul_ln23_1_fu_446_p0;
wire  signed [11:0] mul_ln23_1_fu_446_p1;
wire   [26:0] shl_ln3_fu_453_p3;
wire   [26:0] shl_ln23_1_fu_464_p3;
wire  signed [27:0] sext_ln23_fu_460_p1;
wire  signed [27:0] sext_ln23_1_fu_471_p1;
wire   [27:0] tim_fu_475_p2;
wire   [26:0] shl_ln4_fu_485_p3;
wire  signed [28:0] sext_ln29_fu_450_p1;
wire  signed [28:0] sext_ln31_fu_492_p1;
wire   [26:0] shl_ln31_1_fu_502_p3;
wire  signed [28:0] sext_ln29_1_fu_481_p1;
wire  signed [28:0] sext_ln31_1_fu_509_p1;
wire   [28:0] sre_fu_496_p2;
wire   [27:0] sre_1_fu_531_p4;
wire   [28:0] sim_fu_513_p2;
wire   [27:0] sim_1_fu_545_p4;
wire   [28:0] dre_fu_519_p2;
wire   [27:0] dre_1_fu_559_p4;
wire  signed [28:0] sext_ln31_2_fu_541_p1;
wire  signed [28:0] sre_2_fu_583_p3;
wire  signed [28:0] sext_ln31_3_fu_555_p1;
wire  signed [28:0] sext_ln32_fu_569_p1;
wire  signed [28:0] dre_2_fu_605_p3;
wire  signed [30:0] sext_ln31_4_fu_590_p1;
wire   [0:0] tmp_8_fu_634_p3;
wire   [11:0] trunc_ln8_fu_624_p4;
wire   [11:0] zext_ln34_fu_650_p1;
wire   [0:0] tmp_10_fu_660_p3;
wire   [0:0] tmp_9_fu_642_p3;
wire   [0:0] xor_ln34_fu_668_p2;
wire   [1:0] tmp_13_fu_696_p4;
wire   [0:0] icmp_ln34_1_fu_712_p2;
wire   [0:0] tmp_11_fu_680_p3;
wire   [0:0] tmp_12_fu_688_p3;
wire   [0:0] xor_ln34_1_fu_726_p2;
wire   [0:0] and_ln34_1_fu_732_p2;
wire   [0:0] select_ln34_fu_718_p3;
wire   [0:0] xor_ln34_2_fu_746_p2;
wire   [0:0] or_ln34_fu_752_p2;
wire   [0:0] xor_ln34_3_fu_758_p2;
wire   [0:0] select_ln34_1_fu_738_p3;
wire   [0:0] tmp_15_fu_794_p3;
wire   [11:0] trunc_ln34_1_fu_784_p4;
wire   [11:0] zext_ln34_1_fu_802_p1;
wire   [1:0] tmp_20_fu_820_p4;
wire  signed [30:0] sext_ln32_2_fu_612_p1;
wire   [0:0] tmp_22_fu_860_p3;
wire   [11:0] trunc_ln9_fu_850_p4;
wire   [11:0] zext_ln35_fu_876_p1;
wire   [0:0] tmp_24_fu_886_p3;
wire   [0:0] tmp_23_fu_868_p3;
wire   [0:0] xor_ln35_fu_894_p2;
wire   [1:0] tmp_27_fu_922_p4;
wire   [0:0] icmp_ln35_1_fu_938_p2;
wire   [0:0] tmp_25_fu_906_p3;
wire   [0:0] tmp_26_fu_914_p3;
wire   [0:0] xor_ln35_1_fu_952_p2;
wire   [0:0] and_ln35_1_fu_958_p2;
wire   [0:0] select_ln35_fu_944_p3;
wire   [0:0] xor_ln35_2_fu_972_p2;
wire   [0:0] or_ln35_fu_978_p2;
wire   [0:0] xor_ln35_3_fu_984_p2;
wire   [0:0] select_ln35_1_fu_964_p3;
wire  signed [28:0] sext_ln32_1_fu_1002_p1;
wire  signed [28:0] dim_2_fu_1005_p3;
wire   [0:0] and_ln34_2_fu_1015_p2;
wire   [0:0] or_ln34_4_fu_1019_p2;
wire   [0:0] xor_ln34_4_fu_1024_p2;
wire   [0:0] and_ln34_5_fu_1030_p2;
wire   [0:0] or_ln34_1_fu_1042_p2;
wire   [11:0] select_ln34_2_fu_1035_p3;
wire   [0:0] tmp_16_fu_1055_p3;
wire   [0:0] xor_ln34_5_fu_1062_p2;
wire   [0:0] and_ln34_6_fu_1067_p2;
wire   [0:0] tmp_18_fu_1073_p3;
wire   [0:0] tmp_19_fu_1080_p3;
wire   [0:0] xor_ln34_6_fu_1093_p2;
wire   [0:0] and_ln34_7_fu_1099_p2;
wire   [0:0] select_ln34_4_fu_1087_p3;
wire   [0:0] xor_ln34_7_fu_1117_p2;
wire   [0:0] or_ln34_2_fu_1123_p2;
wire   [0:0] xor_ln34_8_fu_1128_p2;
wire   [0:0] select_ln34_5_fu_1105_p3;
wire   [0:0] and_ln34_8_fu_1112_p2;
wire   [0:0] and_ln34_10_fu_1139_p2;
wire   [0:0] or_ln34_5_fu_1144_p2;
wire   [0:0] xor_ln34_9_fu_1150_p2;
wire   [0:0] and_ln34_9_fu_1133_p2;
wire   [0:0] and_ln34_11_fu_1156_p2;
wire   [0:0] or_ln34_3_fu_1169_p2;
wire   [11:0] select_ln34_6_fu_1161_p3;
wire   [0:0] and_ln35_2_fu_1183_p2;
wire   [0:0] or_ln35_4_fu_1187_p2;
wire   [0:0] xor_ln35_4_fu_1192_p2;
wire   [0:0] and_ln35_5_fu_1198_p2;
wire   [0:0] or_ln35_1_fu_1210_p2;
wire   [11:0] select_ln35_2_fu_1203_p3;
wire  signed [30:0] sext_ln32_3_fu_1011_p1;
wire   [0:0] tmp_29_fu_1240_p3;
wire   [11:0] trunc_ln35_1_fu_1230_p4;
wire   [11:0] zext_ln35_1_fu_1256_p1;
wire   [11:0] add_ln35_1_fu_1260_p2;
wire   [0:0] tmp_31_fu_1266_p3;
wire   [0:0] tmp_30_fu_1248_p3;
wire   [0:0] xor_ln35_5_fu_1274_p2;
wire   [1:0] tmp_34_fu_1302_p4;
wire   [0:0] and_ln35_6_fu_1280_p2;
wire   [0:0] icmp_ln35_2_fu_1312_p2;
wire   [0:0] icmp_ln35_3_fu_1318_p2;
wire   [0:0] tmp_32_fu_1286_p3;
wire   [0:0] tmp_33_fu_1294_p3;
wire   [0:0] xor_ln35_6_fu_1332_p2;
wire   [0:0] and_ln35_7_fu_1338_p2;
wire   [0:0] select_ln35_4_fu_1324_p3;
wire   [0:0] xor_ln35_7_fu_1358_p2;
wire   [0:0] tmp_28_fu_1222_p3;
wire   [0:0] or_ln35_2_fu_1364_p2;
wire   [0:0] xor_ln35_8_fu_1370_p2;
wire   [0:0] select_ln35_5_fu_1344_p3;
wire   [0:0] and_ln35_8_fu_1352_p2;
wire   [0:0] and_ln35_10_fu_1382_p2;
wire   [0:0] or_ln35_5_fu_1388_p2;
wire   [0:0] xor_ln35_9_fu_1394_p2;
wire   [0:0] and_ln35_9_fu_1376_p2;
wire   [0:0] and_ln35_11_fu_1400_p2;
wire   [0:0] or_ln35_3_fu_1414_p2;
wire   [11:0] select_ln35_6_fu_1406_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0;
wire    ap_enable_operation_86;
reg    ap_enable_state15_pp0_iter7_stage0;
wire    ap_enable_operation_90;
reg    ap_enable_state16_pp0_iter7_stage1;
wire    ap_enable_operation_207;
reg    ap_enable_state20_pp0_iter9_stage1;
wire    ap_enable_operation_270;
reg    ap_enable_state22_pp0_iter10_stage1;
wire    ap_enable_operation_87;
wire    ap_enable_operation_91;
wire    ap_enable_operation_229;
wire    ap_enable_operation_271;
wire    ap_enable_operation_97;
reg    ap_enable_state17_pp0_iter8_stage0;
wire    ap_enable_operation_105;
reg    ap_enable_state18_pp0_iter8_stage1;
wire    ap_enable_operation_98;
wire    ap_enable_operation_106;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [25:0] mul_ln22_1_fu_408_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_98 = 8'd0;
#0 s_fu_102 = 4'd0;
#0 indvar_flatten_fu_106 = 11'd0;
#0 ap_done_reg = 1'b0;
end

afdm_mod_top_afdm_mod_Pipeline_stages_butterflies_TW256_INV_re_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
TW256_INV_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TW256_INV_re_address0),
    .ce0(TW256_INV_re_ce0_local),
    .q0(TW256_INV_re_q0)
);

afdm_mod_top_afdm_mod_Pipeline_stages_butterflies_TW256_INV_im_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
TW256_INV_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TW256_INV_im_address0),
    .ce0(TW256_INV_im_ce0_local),
    .q0(TW256_INV_im_q0)
);

afdm_mod_top_udiv_9s_9ns_7_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 7 ))
udiv_9s_9ns_7_13_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(9'd256),
    .din1(grp_fu_312_p1),
    .ce(1'b1),
    .dout(grp_fu_312_p2)
);

afdm_mod_top_mul_7s_7s_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 7 ))
mul_7s_7s_7_1_1_U26(
    .din0(k_reg_1508_pp0_iter6_reg),
    .din1(mul_ln69_fu_374_p1),
    .dout(mul_ln69_fu_374_p2)
);

afdm_mod_top_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U27(
    .din0(TW256_INV_re_load_reg_1561),
    .din1(tmp_re_load_1_reg_1551),
    .dout(mul_ln22_fu_396_p2)
);

afdm_mod_top_mul_15ns_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_15ns_12s_26_1_1_U28(
    .din0(mul_ln22_1_fu_408_p0),
    .din1(tmp_im_load_1_reg_1556),
    .dout(mul_ln22_1_fu_408_p2)
);

afdm_mod_top_mul_15ns_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_15ns_12s_26_1_1_U29(
    .din0(mul_ln23_fu_442_p0),
    .din1(mul_ln23_fu_442_p1),
    .dout(mul_ln23_fu_442_p2)
);

afdm_mod_top_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U30(
    .din0(mul_ln23_1_fu_446_p0),
    .din1(mul_ln23_1_fu_446_p1),
    .dout(mul_ln23_1_fu_446_p2)
);

afdm_mod_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_98 <= 8'd0;
    end else if (((icmp_ln58_reg_1449 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_98 <= i_1_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_204_p2 == 1'd0))) begin
            indvar_flatten_fu_106 <= add_ln58_fu_210_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_106 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_204_p2 == 1'd0))) begin
            s_fu_102 <= select_ln58_2_fu_242_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            s_fu_102 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        TW256_INV_im_load_reg_1566 <= TW256_INV_im_q0;
        TW256_INV_re_load_reg_1561 <= TW256_INV_re_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        k_reg_1508 <= k_fu_321_p2;
        k_reg_1508_pp0_iter1_reg <= k_reg_1508;
        k_reg_1508_pp0_iter2_reg <= k_reg_1508_pp0_iter1_reg;
        k_reg_1508_pp0_iter3_reg <= k_reg_1508_pp0_iter2_reg;
        k_reg_1508_pp0_iter4_reg <= k_reg_1508_pp0_iter3_reg;
        k_reg_1508_pp0_iter5_reg <= k_reg_1508_pp0_iter4_reg;
        k_reg_1508_pp0_iter6_reg <= k_reg_1508_pp0_iter5_reg;
        mul_ln23_1_reg_1633 <= mul_ln23_1_fu_446_p2;
        mul_ln23_reg_1628 <= mul_ln23_fu_442_p2;
        select_ln35_3_reg_1751 <= select_ln35_3_fu_1215_p3;
        select_ln35_7_reg_1756 <= select_ln35_7_fu_1420_p3;
        tre_reg_1623[27 : 1] <= tre_fu_436_p2[27 : 1];
        trunc_ln67_reg_1514 <= trunc_ln67_fu_338_p1;
        trunc_ln67_reg_1514_pp0_iter1_reg <= trunc_ln67_reg_1514;
        trunc_ln67_reg_1514_pp0_iter2_reg <= trunc_ln67_reg_1514_pp0_iter1_reg;
        trunc_ln67_reg_1514_pp0_iter3_reg <= trunc_ln67_reg_1514_pp0_iter2_reg;
        trunc_ln67_reg_1514_pp0_iter4_reg <= trunc_ln67_reg_1514_pp0_iter3_reg;
        trunc_ln67_reg_1514_pp0_iter5_reg <= trunc_ln67_reg_1514_pp0_iter4_reg;
        trunc_ln67_reg_1514_pp0_iter6_reg <= trunc_ln67_reg_1514_pp0_iter5_reg;
        udiv_ln69_reg_1519 <= grp_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln34_1_reg_1696 <= add_ln34_1_fu_806_p2;
        add_ln34_reg_1664 <= add_ln34_fu_654_p2;
        add_ln35_reg_1725 <= add_ln35_fu_880_p2;
        add_ln67_1_reg_1469 <= add_ln67_1_fu_236_p2;
        and_ln34_3_reg_1679 <= and_ln34_3_fu_764_p2;
        and_ln34_4_reg_1685 <= and_ln34_4_fu_770_p2;
        and_ln34_reg_1669 <= and_ln34_fu_674_p2;
        and_ln35_3_reg_1740 <= and_ln35_3_fu_990_p2;
        and_ln35_4_reg_1746 <= and_ln35_4_fu_996_p2;
        and_ln35_reg_1730 <= and_ln35_fu_900_p2;
        bot_im_reg_1535 <= zext_ln69_2_fu_368_p1;
        bot_im_reg_1535_pp0_iter10_reg <= bot_im_reg_1535_pp0_iter9_reg;
        bot_im_reg_1535_pp0_iter8_reg <= bot_im_reg_1535;
        bot_im_reg_1535_pp0_iter9_reg <= bot_im_reg_1535_pp0_iter8_reg;
        bot_re_reg_1529 <= zext_ln69_2_fu_368_p1;
        bot_re_reg_1529_pp0_iter10_reg <= bot_re_reg_1529_pp0_iter9_reg;
        bot_re_reg_1529_pp0_iter8_reg <= bot_re_reg_1529;
        bot_re_reg_1529_pp0_iter9_reg <= bot_re_reg_1529_pp0_iter8_reg;
        dim_1_reg_1643 <= {{dim_fu_525_p2[28:1]}};
        dim_reg_1638[28 : 1] <= dim_fu_525_p2[28 : 1];
        half_reg_1487 <= half_fu_258_p2;
        half_reg_1487_pp0_iter1_reg <= half_reg_1487;
        half_reg_1487_pp0_iter2_reg <= half_reg_1487_pp0_iter1_reg;
        half_reg_1487_pp0_iter3_reg <= half_reg_1487_pp0_iter2_reg;
        half_reg_1487_pp0_iter4_reg <= half_reg_1487_pp0_iter3_reg;
        half_reg_1487_pp0_iter5_reg <= half_reg_1487_pp0_iter4_reg;
        half_reg_1487_pp0_iter6_reg <= half_reg_1487_pp0_iter5_reg;
        ia_reg_1524 <= ia_fu_358_p2;
        icmp_ln34_2_reg_1708 <= icmp_ln34_2_fu_830_p2;
        icmp_ln34_3_reg_1715 <= icmp_ln34_3_fu_836_p2;
        icmp_ln34_reg_1674 <= icmp_ln34_fu_706_p2;
        icmp_ln35_reg_1735 <= icmp_ln35_fu_932_p2;
        icmp_ln58_reg_1449 <= icmp_ln58_fu_204_p2;
        icmp_ln61_reg_1458 <= icmp_ln61_fu_222_p2;
        mul_ln22_1_reg_1608 <= mul_ln22_1_fu_408_p2;
        mul_ln22_reg_1593 <= mul_ln22_fu_396_p2;
        s_load_reg_1453 <= ap_sig_allocacmp_s_load;
        select_ln58_2_reg_1474 <= select_ln58_2_fu_242_p3;
        select_ln58_reg_1463 <= select_ln58_fu_228_p3;
        sext_ln22_1_reg_1588 <= sext_ln22_1_fu_393_p1;
        sext_ln22_3_reg_1603 <= sext_ln22_3_fu_405_p1;
        sext_ln22_reg_1583 <= sext_ln22_fu_390_p1;
        sext_ln31_5_reg_1653 <= sext_ln31_5_fu_601_p1;
        sim_2_reg_1648 <= sim_2_fu_594_p3;
        tmp_14_reg_1690 <= sext_ln31_5_fu_601_p1[32'd30];
        tmp_17_reg_1701 <= add_ln34_1_fu_806_p2[32'd11];
        tmp_21_reg_1720 <= sext_ln32_2_fu_612_p1[32'd30];
        tmp_reg_1659 <= sext_ln31_4_fu_590_p1[32'd30];
        top_im_reg_1577 <= zext_ln69_1_fu_385_p1;
        top_im_reg_1577_pp0_iter9_reg <= top_im_reg_1577;
        top_re_reg_1571 <= zext_ln69_1_fu_385_p1;
        top_re_reg_1571_pp0_iter9_reg <= top_re_reg_1571;
        trunc_ln58_reg_1479 <= trunc_ln58_fu_254_p1;
        trunc_ln58_reg_1479_pp0_iter1_reg <= trunc_ln58_reg_1479;
        trunc_ln58_reg_1479_pp0_iter2_reg <= trunc_ln58_reg_1479_pp0_iter1_reg;
        trunc_ln58_reg_1479_pp0_iter3_reg <= trunc_ln58_reg_1479_pp0_iter2_reg;
        trunc_ln58_reg_1479_pp0_iter4_reg <= trunc_ln58_reg_1479_pp0_iter3_reg;
        trunc_ln58_reg_1479_pp0_iter5_reg <= trunc_ln58_reg_1479_pp0_iter4_reg;
        trunc_ln58_reg_1479_pp0_iter6_reg <= trunc_ln58_reg_1479_pp0_iter5_reg;
        trunc_ln58_reg_1479_pp0_iter7_reg <= trunc_ln58_reg_1479_pp0_iter6_reg;
        trunc_ln58_reg_1479_pp0_iter8_reg <= trunc_ln58_reg_1479_pp0_iter7_reg;
        trunc_ln58_reg_1479_pp0_iter9_reg <= trunc_ln58_reg_1479_pp0_iter8_reg;
        trunc_ln59_reg_1493 <= trunc_ln59_fu_264_p1;
        trunc_ln61_reg_1498 <= trunc_ln61_fu_268_p1;
        zext_ln22_reg_1598[14 : 0] <= zext_ln22_fu_402_p1[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_load_1_reg_1556 <= tmp_im_q1;
        tmp_re_load_1_reg_1551 <= tmp_re_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_load_reg_1618 <= tmp_im_q0;
        tmp_re_load_reg_1613 <= tmp_re_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW256_INV_im_ce0_local = 1'b1;
    end else begin
        TW256_INV_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TW256_INV_re_ce0_local = 1'b1;
    end else begin
        TW256_INV_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_reg_1449 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s_load = 4'd0;
    end else begin
        ap_sig_allocacmp_s_load = s_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_address0_local = bot_im_reg_1535_pp0_iter10_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_im_address0_local = zext_ln69_1_fu_385_p1;
    end else begin
        tmp_im_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_address1_local = top_im_reg_1577_pp0_iter9_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_im_address1_local = zext_ln69_2_fu_368_p1;
    end else begin
        tmp_im_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        tmp_im_ce0_local = 1'b1;
    end else begin
        tmp_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        tmp_im_ce1_local = 1'b1;
    end else begin
        tmp_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_we0_local = 1'b1;
    end else begin
        tmp_im_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_we1_local = 1'b1;
    end else begin
        tmp_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_re_address0_local = bot_re_reg_1529_pp0_iter10_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_re_address0_local = zext_ln69_1_fu_385_p1;
    end else begin
        tmp_re_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_re_address1_local = top_re_reg_1571_pp0_iter9_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_re_address1_local = zext_ln69_2_fu_368_p1;
    end else begin
        tmp_re_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        tmp_re_ce0_local = 1'b1;
    end else begin
        tmp_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        tmp_re_ce1_local = 1'b1;
    end else begin
        tmp_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_re_we0_local = 1'b1;
    end else begin
        tmp_re_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_re_we1_local = 1'b1;
    end else begin
        tmp_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TW256_INV_im_address0 = zext_ln69_3_fu_379_p1;

assign TW256_INV_re_address0 = zext_ln69_3_fu_379_p1;

assign add_ln34_1_fu_806_p2 = (trunc_ln34_1_fu_784_p4 + zext_ln34_1_fu_802_p1);

assign add_ln34_fu_654_p2 = (trunc_ln8_fu_624_p4 + zext_ln34_fu_650_p1);

assign add_ln35_1_fu_1260_p2 = (trunc_ln35_1_fu_1230_p4 + zext_ln35_1_fu_1256_p1);

assign add_ln35_fu_880_p2 = (trunc_ln9_fu_850_p4 + zext_ln35_fu_876_p1);

assign add_ln58_fu_210_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln66_fu_296_p2 = ($signed(trunc_ln59_reg_1493) + $signed(7'd127));

assign add_ln67_1_fu_236_p2 = (ap_sig_allocacmp_s_load + 4'd1);

assign add_ln67_fu_282_p2 = (s_load_reg_1453 + 4'd2);

assign and_ln34_10_fu_1139_p2 = (tmp_17_reg_1701 & select_ln34_5_fu_1105_p3);

assign and_ln34_11_fu_1156_p2 = (xor_ln34_9_fu_1150_p2 & tmp_14_reg_1690);

assign and_ln34_1_fu_732_p2 = (xor_ln34_1_fu_726_p2 & tmp_12_fu_688_p3);

assign and_ln34_2_fu_1015_p2 = (icmp_ln34_reg_1674 & and_ln34_reg_1669);

assign and_ln34_3_fu_764_p2 = (xor_ln34_3_fu_758_p2 & or_ln34_fu_752_p2);

assign and_ln34_4_fu_770_p2 = (tmp_10_fu_660_p3 & select_ln34_1_fu_738_p3);

assign and_ln34_5_fu_1030_p2 = (xor_ln34_4_fu_1024_p2 & tmp_reg_1659);

assign and_ln34_6_fu_1067_p2 = (xor_ln34_5_fu_1062_p2 & tmp_16_fu_1055_p3);

assign and_ln34_7_fu_1099_p2 = (xor_ln34_6_fu_1093_p2 & tmp_19_fu_1080_p3);

assign and_ln34_8_fu_1112_p2 = (icmp_ln34_2_reg_1708 & and_ln34_6_fu_1067_p2);

assign and_ln34_9_fu_1133_p2 = (xor_ln34_8_fu_1128_p2 & or_ln34_2_fu_1123_p2);

assign and_ln34_fu_674_p2 = (xor_ln34_fu_668_p2 & tmp_9_fu_642_p3);

assign and_ln35_10_fu_1382_p2 = (tmp_31_fu_1266_p3 & select_ln35_5_fu_1344_p3);

assign and_ln35_11_fu_1400_p2 = (xor_ln35_9_fu_1394_p2 & tmp_28_fu_1222_p3);

assign and_ln35_1_fu_958_p2 = (xor_ln35_1_fu_952_p2 & tmp_26_fu_914_p3);

assign and_ln35_2_fu_1183_p2 = (icmp_ln35_reg_1735 & and_ln35_reg_1730);

assign and_ln35_3_fu_990_p2 = (xor_ln35_3_fu_984_p2 & or_ln35_fu_978_p2);

assign and_ln35_4_fu_996_p2 = (tmp_24_fu_886_p3 & select_ln35_1_fu_964_p3);

assign and_ln35_5_fu_1198_p2 = (xor_ln35_4_fu_1192_p2 & tmp_21_reg_1720);

assign and_ln35_6_fu_1280_p2 = (xor_ln35_5_fu_1274_p2 & tmp_30_fu_1248_p3);

assign and_ln35_7_fu_1338_p2 = (xor_ln35_6_fu_1332_p2 & tmp_33_fu_1294_p3);

assign and_ln35_8_fu_1352_p2 = (icmp_ln35_2_fu_1312_p2 & and_ln35_6_fu_1280_p2);

assign and_ln35_9_fu_1376_p2 = (xor_ln35_8_fu_1370_p2 & or_ln35_2_fu_1364_p2);

assign and_ln35_fu_900_p2 = (xor_ln35_fu_894_p2 & tmp_23_fu_868_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_operation_105 = (1'b1 == 1'b1);

assign ap_enable_operation_106 = (1'b1 == 1'b1);

assign ap_enable_operation_207 = (1'b1 == 1'b1);

assign ap_enable_operation_229 = (1'b1 == 1'b1);

assign ap_enable_operation_270 = (1'b1 == 1'b1);

assign ap_enable_operation_271 = (1'b1 == 1'b1);

assign ap_enable_operation_86 = (1'b1 == 1'b1);

assign ap_enable_operation_87 = (1'b1 == 1'b1);

assign ap_enable_operation_90 = (1'b1 == 1'b1);

assign ap_enable_operation_91 = (1'b1 == 1'b1);

assign ap_enable_operation_97 = (1'b1 == 1'b1);

assign ap_enable_operation_98 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state15_pp0_iter7_stage0 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state16_pp0_iter7_stage1 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state17_pp0_iter8_stage0 = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state18_pp0_iter8_stage1 = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state20_pp0_iter9_stage1 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state22_pp0_iter10_stage1 = ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign dim_2_fu_1005_p3 = ((trunc_ln58_reg_1479_pp0_iter9_reg[0:0] == 1'b1) ? dim_reg_1638 : sext_ln32_1_fu_1002_p1);

assign dim_fu_525_p2 = ($signed(sext_ln31_1_fu_509_p1) - $signed(sext_ln29_1_fu_481_p1));

assign dre_1_fu_559_p4 = {{dre_fu_519_p2[28:1]}};

assign dre_2_fu_605_p3 = ((trunc_ln58_reg_1479_pp0_iter8_reg[0:0] == 1'b1) ? dre_fu_519_p2 : sext_ln32_fu_569_p1);

assign dre_fu_519_p2 = ($signed(sext_ln31_fu_492_p1) - $signed(sext_ln29_fu_450_p1));

assign grp_fu_312_p1 = {{half_reg_1487}, {1'd0}};

assign half_fu_258_p2 = 8'd1 << zext_ln58_1_fu_250_p1;

assign i_1_fu_342_p2 = (select_ln58_reg_1463 + 8'd1);

assign ia_fu_358_p2 = (trunc_ln67_reg_1514_pp0_iter6_reg + zext_ln66_fu_355_p1);

assign ib_fu_363_p2 = (ia_fu_358_p2 + half_reg_1487_pp0_iter6_reg);

assign icmp_ln34_1_fu_712_p2 = ((tmp_13_fu_696_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_2_fu_830_p2 = ((tmp_20_fu_820_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln34_3_fu_836_p2 = ((tmp_20_fu_820_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_706_p2 = ((tmp_13_fu_696_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln35_1_fu_938_p2 = ((tmp_27_fu_922_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_2_fu_1312_p2 = ((tmp_34_fu_1302_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln35_3_fu_1318_p2 = ((tmp_34_fu_1302_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_932_p2 = ((tmp_27_fu_922_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_204_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_222_p2 = ((ap_sig_allocacmp_i_load == 8'd128) ? 1'b1 : 1'b0);

assign k_fu_321_p2 = (trunc_ln61_reg_1498 & add_ln66_fu_296_p2);

assign lshr_ln67_fu_326_p2 = zext_ln61_fu_318_p1 >> zext_ln58_fu_293_p1;

assign mul_ln22_1_fu_408_p0 = mul_ln22_1_fu_408_p00;

assign mul_ln22_1_fu_408_p00 = TW256_INV_im_load_reg_1566;

assign mul_ln23_1_fu_446_p0 = sext_ln22_reg_1583;

assign mul_ln23_1_fu_446_p1 = sext_ln22_3_reg_1603;

assign mul_ln23_fu_442_p0 = zext_ln22_reg_1598;

assign mul_ln23_fu_442_p1 = sext_ln22_1_reg_1588;

assign mul_ln69_fu_374_p1 = udiv_ln69_reg_1519[6:0];

assign or_ln34_1_fu_1042_p2 = (and_ln34_5_fu_1030_p2 | and_ln34_3_reg_1679);

assign or_ln34_2_fu_1123_p2 = (xor_ln34_7_fu_1117_p2 | tmp_17_reg_1701);

assign or_ln34_3_fu_1169_p2 = (and_ln34_9_fu_1133_p2 | and_ln34_11_fu_1156_p2);

assign or_ln34_4_fu_1019_p2 = (and_ln34_4_reg_1685 | and_ln34_2_fu_1015_p2);

assign or_ln34_5_fu_1144_p2 = (and_ln34_8_fu_1112_p2 | and_ln34_10_fu_1139_p2);

assign or_ln34_fu_752_p2 = (xor_ln34_2_fu_746_p2 | tmp_10_fu_660_p3);

assign or_ln35_1_fu_1210_p2 = (and_ln35_5_fu_1198_p2 | and_ln35_3_reg_1740);

assign or_ln35_2_fu_1364_p2 = (xor_ln35_7_fu_1358_p2 | tmp_31_fu_1266_p3);

assign or_ln35_3_fu_1414_p2 = (and_ln35_9_fu_1376_p2 | and_ln35_11_fu_1400_p2);

assign or_ln35_4_fu_1187_p2 = (and_ln35_4_reg_1746 | and_ln35_2_fu_1183_p2);

assign or_ln35_5_fu_1388_p2 = (and_ln35_8_fu_1352_p2 | and_ln35_10_fu_1382_p2);

assign or_ln35_fu_978_p2 = (xor_ln35_2_fu_972_p2 | tmp_24_fu_886_p3);

assign select_ln34_1_fu_738_p3 = ((and_ln34_fu_674_p2[0:0] == 1'b1) ? and_ln34_1_fu_732_p2 : icmp_ln34_fu_706_p2);

assign select_ln34_2_fu_1035_p3 = ((and_ln34_3_reg_1679[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign select_ln34_3_fu_1047_p3 = ((or_ln34_1_fu_1042_p2[0:0] == 1'b1) ? select_ln34_2_fu_1035_p3 : add_ln34_reg_1664);

assign select_ln34_4_fu_1087_p3 = ((and_ln34_6_fu_1067_p2[0:0] == 1'b1) ? icmp_ln34_2_reg_1708 : icmp_ln34_3_reg_1715);

assign select_ln34_5_fu_1105_p3 = ((and_ln34_6_fu_1067_p2[0:0] == 1'b1) ? and_ln34_7_fu_1099_p2 : icmp_ln34_2_reg_1708);

assign select_ln34_6_fu_1161_p3 = ((and_ln34_9_fu_1133_p2[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign select_ln34_7_fu_1175_p3 = ((or_ln34_3_fu_1169_p2[0:0] == 1'b1) ? select_ln34_6_fu_1161_p3 : add_ln34_1_reg_1696);

assign select_ln34_fu_718_p3 = ((and_ln34_fu_674_p2[0:0] == 1'b1) ? icmp_ln34_fu_706_p2 : icmp_ln34_1_fu_712_p2);

assign select_ln35_1_fu_964_p3 = ((and_ln35_fu_900_p2[0:0] == 1'b1) ? and_ln35_1_fu_958_p2 : icmp_ln35_fu_932_p2);

assign select_ln35_2_fu_1203_p3 = ((and_ln35_3_reg_1740[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign select_ln35_3_fu_1215_p3 = ((or_ln35_1_fu_1210_p2[0:0] == 1'b1) ? select_ln35_2_fu_1203_p3 : add_ln35_reg_1725);

assign select_ln35_4_fu_1324_p3 = ((and_ln35_6_fu_1280_p2[0:0] == 1'b1) ? icmp_ln35_2_fu_1312_p2 : icmp_ln35_3_fu_1318_p2);

assign select_ln35_5_fu_1344_p3 = ((and_ln35_6_fu_1280_p2[0:0] == 1'b1) ? and_ln35_7_fu_1338_p2 : icmp_ln35_2_fu_1312_p2);

assign select_ln35_6_fu_1406_p3 = ((and_ln35_9_fu_1376_p2[0:0] == 1'b1) ? 12'd2047 : 12'd2048);

assign select_ln35_7_fu_1420_p3 = ((or_ln35_3_fu_1414_p2[0:0] == 1'b1) ? select_ln35_6_fu_1406_p3 : add_ln35_1_fu_1260_p2);

assign select_ln35_fu_944_p3 = ((and_ln35_fu_900_p2[0:0] == 1'b1) ? icmp_ln35_fu_932_p2 : icmp_ln35_1_fu_938_p2);

assign select_ln58_1_fu_287_p3 = ((icmp_ln61_reg_1458[0:0] == 1'b1) ? add_ln67_fu_282_p2 : add_ln67_1_reg_1469);

assign select_ln58_2_fu_242_p3 = ((icmp_ln61_fu_222_p2[0:0] == 1'b1) ? add_ln67_1_fu_236_p2 : ap_sig_allocacmp_s_load);

assign select_ln58_fu_228_p3 = ((icmp_ln61_fu_222_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_i_load);

assign sext_ln22_1_fu_393_p1 = tmp_re_load_1_reg_1551;

assign sext_ln22_2_fu_421_p1 = $signed(shl_ln2_fu_414_p3);

assign sext_ln22_3_fu_405_p1 = tmp_im_load_1_reg_1556;

assign sext_ln22_4_fu_432_p1 = $signed(shl_ln22_1_fu_425_p3);

assign sext_ln22_fu_390_p1 = TW256_INV_re_load_reg_1561;

assign sext_ln23_1_fu_471_p1 = $signed(shl_ln23_1_fu_464_p3);

assign sext_ln23_fu_460_p1 = $signed(shl_ln3_fu_453_p3);

assign sext_ln29_1_fu_481_p1 = $signed(tim_fu_475_p2);

assign sext_ln29_fu_450_p1 = $signed(tre_reg_1623);

assign sext_ln31_1_fu_509_p1 = $signed(shl_ln31_1_fu_502_p3);

assign sext_ln31_2_fu_541_p1 = $signed(sre_1_fu_531_p4);

assign sext_ln31_3_fu_555_p1 = $signed(sim_1_fu_545_p4);

assign sext_ln31_4_fu_590_p1 = sre_2_fu_583_p3;

assign sext_ln31_5_fu_601_p1 = sim_2_fu_594_p3;

assign sext_ln31_fu_492_p1 = $signed(shl_ln4_fu_485_p3);

assign sext_ln32_1_fu_1002_p1 = $signed(dim_1_reg_1643);

assign sext_ln32_2_fu_612_p1 = dre_2_fu_605_p3;

assign sext_ln32_3_fu_1011_p1 = dim_2_fu_1005_p3;

assign sext_ln32_fu_569_p1 = $signed(dre_1_fu_559_p4);

assign shl_ln22_1_fu_425_p3 = {{mul_ln22_1_reg_1608}, {1'd0}};

assign shl_ln23_1_fu_464_p3 = {{mul_ln23_1_reg_1633}, {1'd0}};

assign shl_ln2_fu_414_p3 = {{mul_ln22_reg_1593}, {1'd0}};

assign shl_ln31_1_fu_502_p3 = {{tmp_im_load_reg_1618}, {15'd0}};

assign shl_ln3_fu_453_p3 = {{mul_ln23_reg_1628}, {1'd0}};

assign shl_ln4_fu_485_p3 = {{tmp_re_load_reg_1613}, {15'd0}};

assign shl_ln67_fu_332_p2 = lshr_ln67_fu_326_p2 << zext_ln69_fu_301_p1;

assign sim_1_fu_545_p4 = {{sim_fu_513_p2[28:1]}};

assign sim_2_fu_594_p3 = ((trunc_ln58_reg_1479_pp0_iter8_reg[0:0] == 1'b1) ? sim_fu_513_p2 : sext_ln31_3_fu_555_p1);

assign sim_fu_513_p2 = ($signed(sext_ln29_1_fu_481_p1) + $signed(sext_ln31_1_fu_509_p1));

assign sre_1_fu_531_p4 = {{sre_fu_496_p2[28:1]}};

assign sre_2_fu_583_p3 = ((trunc_ln58_reg_1479_pp0_iter8_reg[0:0] == 1'b1) ? sre_fu_496_p2 : sext_ln31_2_fu_541_p1);

assign sre_fu_496_p2 = ($signed(sext_ln29_fu_450_p1) + $signed(sext_ln31_fu_492_p1));

assign tim_fu_475_p2 = ($signed(sext_ln23_fu_460_p1) + $signed(sext_ln23_1_fu_471_p1));

assign tmp_10_fu_660_p3 = add_ln34_fu_654_p2[32'd11];

assign tmp_11_fu_680_p3 = sext_ln31_4_fu_590_p1[32'd27];

assign tmp_12_fu_688_p3 = sre_2_fu_583_p3[32'd28];

assign tmp_13_fu_696_p4 = {{sre_2_fu_583_p3[28:27]}};

assign tmp_15_fu_794_p3 = sext_ln31_5_fu_601_p1[32'd14];

assign tmp_16_fu_1055_p3 = sext_ln31_5_reg_1653[32'd26];

assign tmp_18_fu_1073_p3 = sext_ln31_5_reg_1653[32'd27];

assign tmp_19_fu_1080_p3 = sim_2_reg_1648[32'd28];

assign tmp_20_fu_820_p4 = {{sim_2_fu_594_p3[28:27]}};

assign tmp_21_fu_842_p3 = sext_ln32_2_fu_612_p1[32'd30];

assign tmp_22_fu_860_p3 = sext_ln32_2_fu_612_p1[32'd14];

assign tmp_23_fu_868_p3 = sext_ln32_2_fu_612_p1[32'd26];

assign tmp_24_fu_886_p3 = add_ln35_fu_880_p2[32'd11];

assign tmp_25_fu_906_p3 = sext_ln32_2_fu_612_p1[32'd27];

assign tmp_26_fu_914_p3 = dre_2_fu_605_p3[32'd28];

assign tmp_27_fu_922_p4 = {{dre_2_fu_605_p3[28:27]}};

assign tmp_28_fu_1222_p3 = sext_ln32_3_fu_1011_p1[32'd30];

assign tmp_29_fu_1240_p3 = sext_ln32_3_fu_1011_p1[32'd14];

assign tmp_30_fu_1248_p3 = sext_ln32_3_fu_1011_p1[32'd26];

assign tmp_31_fu_1266_p3 = add_ln35_1_fu_1260_p2[32'd11];

assign tmp_32_fu_1286_p3 = sext_ln32_3_fu_1011_p1[32'd27];

assign tmp_33_fu_1294_p3 = dim_2_fu_1005_p3[32'd28];

assign tmp_34_fu_1302_p4 = {{dim_2_fu_1005_p3[28:27]}};

assign tmp_8_fu_634_p3 = sext_ln31_4_fu_590_p1[32'd14];

assign tmp_9_fu_642_p3 = sext_ln31_4_fu_590_p1[32'd26];

assign tmp_fu_616_p3 = sext_ln31_4_fu_590_p1[32'd30];

assign tmp_im_address0 = tmp_im_address0_local;

assign tmp_im_address1 = tmp_im_address1_local;

assign tmp_im_ce0 = tmp_im_ce0_local;

assign tmp_im_ce1 = tmp_im_ce1_local;

assign tmp_im_d0 = select_ln35_7_reg_1756;

assign tmp_im_d1 = select_ln34_7_fu_1175_p3;

assign tmp_im_we0 = tmp_im_we0_local;

assign tmp_im_we1 = tmp_im_we1_local;

assign tmp_re_address0 = tmp_re_address0_local;

assign tmp_re_address1 = tmp_re_address1_local;

assign tmp_re_ce0 = tmp_re_ce0_local;

assign tmp_re_ce1 = tmp_re_ce1_local;

assign tmp_re_d0 = select_ln35_3_reg_1751;

assign tmp_re_d1 = select_ln34_3_fu_1047_p3;

assign tmp_re_we0 = tmp_re_we0_local;

assign tmp_re_we1 = tmp_re_we1_local;

assign tre_fu_436_p2 = ($signed(sext_ln22_2_fu_421_p1) - $signed(sext_ln22_4_fu_432_p1));

assign trunc_ln34_1_fu_784_p4 = {{sim_2_fu_594_p3[26:15]}};

assign trunc_ln35_1_fu_1230_p4 = {{dim_2_fu_1005_p3[26:15]}};

assign trunc_ln58_fu_254_p1 = select_ln58_2_fu_242_p3[0:0];

assign trunc_ln59_fu_264_p1 = half_fu_258_p2[6:0];

assign trunc_ln61_fu_268_p1 = select_ln58_fu_228_p3[6:0];

assign trunc_ln67_fu_338_p1 = shl_ln67_fu_332_p2[7:0];

assign trunc_ln8_fu_624_p4 = {{sre_2_fu_583_p3[26:15]}};

assign trunc_ln9_fu_850_p4 = {{dre_2_fu_605_p3[26:15]}};

assign xor_ln34_1_fu_726_p2 = (tmp_11_fu_680_p3 ^ 1'd1);

assign xor_ln34_2_fu_746_p2 = (select_ln34_fu_718_p3 ^ 1'd1);

assign xor_ln34_3_fu_758_p2 = (tmp_fu_616_p3 ^ 1'd1);

assign xor_ln34_4_fu_1024_p2 = (or_ln34_4_fu_1019_p2 ^ 1'd1);

assign xor_ln34_5_fu_1062_p2 = (tmp_17_reg_1701 ^ 1'd1);

assign xor_ln34_6_fu_1093_p2 = (tmp_18_fu_1073_p3 ^ 1'd1);

assign xor_ln34_7_fu_1117_p2 = (select_ln34_4_fu_1087_p3 ^ 1'd1);

assign xor_ln34_8_fu_1128_p2 = (tmp_14_reg_1690 ^ 1'd1);

assign xor_ln34_9_fu_1150_p2 = (or_ln34_5_fu_1144_p2 ^ 1'd1);

assign xor_ln34_fu_668_p2 = (tmp_10_fu_660_p3 ^ 1'd1);

assign xor_ln35_1_fu_952_p2 = (tmp_25_fu_906_p3 ^ 1'd1);

assign xor_ln35_2_fu_972_p2 = (select_ln35_fu_944_p3 ^ 1'd1);

assign xor_ln35_3_fu_984_p2 = (tmp_21_fu_842_p3 ^ 1'd1);

assign xor_ln35_4_fu_1192_p2 = (or_ln35_4_fu_1187_p2 ^ 1'd1);

assign xor_ln35_5_fu_1274_p2 = (tmp_31_fu_1266_p3 ^ 1'd1);

assign xor_ln35_6_fu_1332_p2 = (tmp_32_fu_1286_p3 ^ 1'd1);

assign xor_ln35_7_fu_1358_p2 = (select_ln35_4_fu_1324_p3 ^ 1'd1);

assign xor_ln35_8_fu_1370_p2 = (tmp_28_fu_1222_p3 ^ 1'd1);

assign xor_ln35_9_fu_1394_p2 = (or_ln35_5_fu_1388_p2 ^ 1'd1);

assign xor_ln35_fu_894_p2 = (tmp_24_fu_886_p3 ^ 1'd1);

assign zext_ln22_fu_402_p1 = TW256_INV_im_load_reg_1566;

assign zext_ln34_1_fu_802_p1 = tmp_15_fu_794_p3;

assign zext_ln34_fu_650_p1 = tmp_8_fu_634_p3;

assign zext_ln35_1_fu_1256_p1 = tmp_29_fu_1240_p3;

assign zext_ln35_fu_876_p1 = tmp_22_fu_860_p3;

assign zext_ln58_1_fu_250_p1 = select_ln58_2_fu_242_p3;

assign zext_ln58_fu_293_p1 = select_ln58_2_reg_1474;

assign zext_ln61_fu_318_p1 = select_ln58_reg_1463;

assign zext_ln66_fu_355_p1 = $unsigned(k_reg_1508_pp0_iter6_reg);

assign zext_ln69_1_fu_385_p1 = ia_reg_1524;

assign zext_ln69_2_fu_368_p1 = ib_fu_363_p2;

assign zext_ln69_3_fu_379_p1 = mul_ln69_fu_374_p2;

assign zext_ln69_fu_301_p1 = select_ln58_1_fu_287_p3;

always @ (posedge ap_clk) begin
    zext_ln22_reg_1598[25:15] <= 11'b00000000000;
    tre_reg_1623[0] <= 1'b0;
    dim_reg_1638[0] <= 1'b0;
end

endmodule //afdm_mod_top_afdm_mod_Pipeline_stages_butterflies
