// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module afdm_mod_top_afdm_mod_Pipeline_post_chirp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_re_address0,
        buf_re_ce0,
        buf_re_q0,
        buf_im_address0,
        buf_im_ce0,
        buf_im_q0,
        s_re_address0,
        s_re_ce0,
        s_re_we0,
        s_re_d0,
        s_im_address0,
        s_im_ce0,
        s_im_we0,
        s_im_d0,
        grp_chirp_mul_fu_104_p_din1,
        grp_chirp_mul_fu_104_p_din2,
        grp_chirp_mul_fu_104_p_din3,
        grp_chirp_mul_fu_104_p_din4,
        grp_chirp_mul_fu_104_p_dout0_0,
        grp_chirp_mul_fu_104_p_dout0_1,
        grp_chirp_mul_fu_104_p_start,
        grp_chirp_mul_fu_104_p_ready,
        grp_chirp_mul_fu_104_p_done,
        grp_chirp_mul_fu_104_p_idle
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] buf_re_address0;
output   buf_re_ce0;
input  [11:0] buf_re_q0;
output  [7:0] buf_im_address0;
output   buf_im_ce0;
input  [11:0] buf_im_q0;
output  [7:0] s_re_address0;
output   s_re_ce0;
output   s_re_we0;
output  [11:0] s_re_d0;
output  [7:0] s_im_address0;
output   s_im_ce0;
output   s_im_we0;
output  [11:0] s_im_d0;
output  [11:0] grp_chirp_mul_fu_104_p_din1;
output  [11:0] grp_chirp_mul_fu_104_p_din2;
output  [15:0] grp_chirp_mul_fu_104_p_din3;
output  [14:0] grp_chirp_mul_fu_104_p_din4;
input  [11:0] grp_chirp_mul_fu_104_p_dout0_0;
input  [11:0] grp_chirp_mul_fu_104_p_dout0_1;
output   grp_chirp_mul_fu_104_p_start;
input   grp_chirp_mul_fu_104_p_ready;
input   grp_chirp_mul_fu_104_p_done;
input   grp_chirp_mul_fu_104_p_idle;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_138_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] CHIRP1_re_address0;
wire   [15:0] CHIRP1_re_q0;
wire   [7:0] CHIRP1_im_address0;
wire   [14:0] CHIRP1_im_q0;
reg   [0:0] icmp_ln31_reg_178;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln31_fu_150_p1;
reg   [63:0] zext_ln31_reg_182;
reg   [63:0] zext_ln31_reg_182_pp0_iter1_reg;
reg   [63:0] zext_ln31_reg_182_pp0_iter2_reg;
reg   [63:0] zext_ln31_reg_182_pp0_iter3_reg;
reg   [11:0] buf_re_load_reg_208;
reg   [11:0] buf_im_load_reg_213;
reg   [15:0] CHIRP1_re_load_reg_218;
reg   [14:0] CHIRP1_im_load_reg_223;
reg   [11:0] ref_tmp1_reg_228;
reg   [11:0] ref_tmp10_1_reg_233;
wire    grp_chirp_mul_fu_122_ap_ready;
reg    grp_chirp_mul_fu_122_ap_start_reg;
wire    ap_block_pp0_stage0_ignoreCallOp29;
wire    ap_block_pp0_stage0;
reg   [8:0] n_2_fu_40;
wire   [8:0] add_ln31_fu_144_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_n;
reg    buf_re_ce0_local;
reg    buf_im_ce0_local;
reg    CHIRP1_re_ce0_local;
reg    CHIRP1_im_ce0_local;
reg    s_re_we0_local;
reg    s_re_ce0_local;
reg    s_im_we0_local;
reg    s_im_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 grp_chirp_mul_fu_122_ap_start_reg = 1'b0;
#0 n_2_fu_40 = 9'd0;
#0 ap_done_reg = 1'b0;
end

afdm_mod_top_afdm_mod_Pipeline_post_chirp_CHIRP1_re_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
CHIRP1_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CHIRP1_re_address0),
    .ce0(CHIRP1_re_ce0_local),
    .q0(CHIRP1_re_q0)
);

afdm_mod_top_afdm_mod_Pipeline_post_chirp_CHIRP1_im_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
CHIRP1_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CHIRP1_im_address0),
    .ce0(CHIRP1_im_ce0_local),
    .q0(CHIRP1_im_q0)
);

afdm_mod_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_chirp_mul_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln31_reg_178 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_chirp_mul_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_chirp_mul_fu_122_ap_ready == 1'b1)) begin
            grp_chirp_mul_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln31_fu_138_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_2_fu_40 <= add_ln31_fu_144_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_2_fu_40 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CHIRP1_im_load_reg_223 <= CHIRP1_im_q0;
        CHIRP1_re_load_reg_218 <= CHIRP1_re_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        buf_im_load_reg_213 <= buf_im_q0;
        buf_re_load_reg_208 <= buf_re_q0;
        icmp_ln31_reg_178 <= icmp_ln31_fu_138_p2;
        zext_ln31_reg_182[8 : 0] <= zext_ln31_fu_150_p1[8 : 0];
        zext_ln31_reg_182_pp0_iter1_reg[8 : 0] <= zext_ln31_reg_182[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ref_tmp10_1_reg_233 <= grp_chirp_mul_fu_104_p_dout0_1;
        ref_tmp1_reg_228 <= grp_chirp_mul_fu_104_p_dout0_0;
        zext_ln31_reg_182_pp0_iter2_reg[8 : 0] <= zext_ln31_reg_182_pp0_iter1_reg[8 : 0];
        zext_ln31_reg_182_pp0_iter3_reg[8 : 0] <= zext_ln31_reg_182_pp0_iter2_reg[8 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CHIRP1_im_ce0_local = 1'b1;
    end else begin
        CHIRP1_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CHIRP1_re_ce0_local = 1'b1;
    end else begin
        CHIRP1_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_138_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n = 9'd0;
    end else begin
        ap_sig_allocacmp_n = n_2_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_im_ce0_local = 1'b1;
    end else begin
        buf_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_re_ce0_local = 1'b1;
    end else begin
        buf_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_im_ce0_local = 1'b1;
    end else begin
        s_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_im_we0_local = 1'b1;
    end else begin
        s_im_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_re_ce0_local = 1'b1;
    end else begin
        s_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        s_re_we0_local = 1'b1;
    end else begin
        s_re_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CHIRP1_im_address0 = zext_ln31_fu_150_p1;

assign CHIRP1_re_address0 = zext_ln31_fu_150_p1;

assign add_ln31_fu_144_p2 = (ap_sig_allocacmp_n + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp29 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buf_im_address0 = zext_ln31_fu_150_p1;

assign buf_im_ce0 = buf_im_ce0_local;

assign buf_re_address0 = zext_ln31_fu_150_p1;

assign buf_re_ce0 = buf_re_ce0_local;

assign grp_chirp_mul_fu_104_p_din1 = buf_re_load_reg_208;

assign grp_chirp_mul_fu_104_p_din2 = buf_im_load_reg_213;

assign grp_chirp_mul_fu_104_p_din3 = CHIRP1_re_load_reg_218;

assign grp_chirp_mul_fu_104_p_din4 = CHIRP1_im_load_reg_223;

assign grp_chirp_mul_fu_104_p_start = grp_chirp_mul_fu_122_ap_start_reg;

assign grp_chirp_mul_fu_122_ap_ready = grp_chirp_mul_fu_104_p_ready;

assign icmp_ln31_fu_138_p2 = ((ap_sig_allocacmp_n == 9'd256) ? 1'b1 : 1'b0);

assign s_im_address0 = zext_ln31_reg_182_pp0_iter3_reg;

assign s_im_ce0 = s_im_ce0_local;

assign s_im_d0 = ref_tmp10_1_reg_233;

assign s_im_we0 = s_im_we0_local;

assign s_re_address0 = zext_ln31_reg_182_pp0_iter3_reg;

assign s_re_ce0 = s_re_ce0_local;

assign s_re_d0 = ref_tmp1_reg_228;

assign s_re_we0 = s_re_we0_local;

assign zext_ln31_fu_150_p1 = ap_sig_allocacmp_n;

always @ (posedge ap_clk) begin
    zext_ln31_reg_182[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln31_reg_182_pp0_iter1_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln31_reg_182_pp0_iter2_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln31_reg_182_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //afdm_mod_top_afdm_mod_Pipeline_post_chirp
